repos:
- repo: local
  hooks:
  - id: sagemaker-rightline
    name: sagemaker-rightline
    entry: sagemaker-rightline
    language: system
    types: [python]
    pass_filenames: false
    args: ['--configuration', 'sm_rightline_config.py', '--working-dir', 'examples/sm_pipeline_project']
