sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /github/home/.config/sagemaker/config.yaml
@startuml sagemaker_rightline
!pragma useIntermediatePackages false

class sagemaker_rightline.model.Configuration {
  validations: List[Validation]
  sagemaker_pipeline: Pipeline
}
class sagemaker_rightline.model.Report {
  results: List[ValidationResult]
}
abstract class sagemaker_rightline.model.Rule {
  name: str
  negative: bool
}
abstract class sagemaker_rightline.model.Validation {
  paths: List[Optional[str]]
  name: str
  rule: Rule
}
class sagemaker_rightline.model.ValidationFailedError {
  validation_result: ValidationResult
  message: None
}
class sagemaker_rightline.model.ValidationResult {
  validation_name: str
  success: bool
  negative: bool
  message: str
  subject: str
}
class sagemaker_rightline.rules.Contains {
}
class sagemaker_rightline.rules.Equals {
}
class sagemaker_rightline.validations.ContainerImage {
  uri: str
}
class sagemaker_rightline.validations.PipelineParametersAsExpected {
  parameters_expected: List[Parameter]
  ignore_default_value: bool
}
class sagemaker_rightline.validations.PipelineProcessingStepsIONamesUnique {
}
class sagemaker_rightline.validations.StepCallbackSqsQueueExists {
  client: None
}
class sagemaker_rightline.validations.StepImagesExist {
  step_filter: str
  client: None
}
class sagemaker_rightline.validations.StepInputsAsExpected {
  step_filter: str
  step_type_filter: str
  inputs_expected: List[Dict[str, Union[str, TrainingInput, ProcessingInput, FileSystemInput]]]
}
class sagemaker_rightline.validations.StepKmsKeyIdAsExpected {
  step_filter: str
  kms_key_id_expected: str
}
class sagemaker_rightline.validations.StepLambdaFunctionExists {
  client: None
}
class sagemaker_rightline.validations.StepNetworkConfigAsExpected {
  step_filter: str
  network_config_expected: NetworkConfig
}
class sagemaker_rightline.validations.StepOutputsAsExpected {
  step_filter: str
  outputs_expected: List[Union[ProcessingOutput, str]]
}
class sagemaker_rightline.validations.StepOutputsMatchInputsAsExpected {
  inputs_outputs_expected: List[Dict[str, Dict[str, str]]]
}
class sagemaker_rightline.validations.StepRoleNameAsExpected {
  step_filter: str
  role_name_expected: str
}
class sagemaker_rightline.validations.StepRoleNameExists {
  step_filter: str
  client: None
}
class sagemaker_rightline.validations.StepTagsAsExpected {
  step_filter: str
  tags_expected: List[Dict[str, Union[str, PipelineVariable]]]
}
sagemaker_rightline.model.Configuration *-- sagemaker_rightline.model.Validation
sagemaker_rightline.model.Report *-- sagemaker_rightline.model.ValidationResult
sagemaker_rightline.model.Validation *-- sagemaker_rightline.model.Rule
sagemaker_rightline.model.ValidationFailedError *-- sagemaker_rightline.model.ValidationResult
sagemaker_rightline.model.Rule <|-- sagemaker_rightline.rules.Contains
sagemaker_rightline.model.Rule <|-- sagemaker_rightline.rules.Equals
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.PipelineParametersAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.PipelineProcessingStepsIONamesUnique
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepCallbackSqsQueueExists
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepImagesExist
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepInputsAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepKmsKeyIdAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepLambdaFunctionExists
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepNetworkConfigAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepOutputsAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepOutputsMatchInputsAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepRoleNameAsExpected
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepRoleNameExists
sagemaker_rightline.model.Validation <|-- sagemaker_rightline.validations.StepTagsAsExpected
footer Generated by //py2puml//
@enduml

