name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Update Pip
      run: pip install -U pip

  Build:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
    - name: Install build
      run: pip install build
    - name: Build Package
      working-directory: ..
      run: python3 -m build

  PyPI-Publish:
    needs: [Build]
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  Ready:
    name: Ready
    needs: [PyPI-Publish]
    uses: ./.github/workflows/ready.yml
    with:
      message: "Package has been published."
