name: Publish to PyPI

on:
  release:
    types: [published]

env:
  DEFAULT_PYTHON_VERSION: "3.10"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
    - name: Update Pip
      run: pip install -U pip
    - name: Install build
      run: pip install build
    - name: Set Version & Build Package
      run: |
        escaped_version=$(echo "${{ github.ref_name}}" | sed 's/[\*\.\[\]\|\(\)\$\\\/]/\\&/g')
        sed -i "s/__version__ = \"0\.0\.0\"/__version__ = \"$escaped_version\"/g" ./sagemaker_rightline/__init__.py
        python3 -m build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist

  PyPI-Publish:
    needs: [Build]
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  Ready:
    name: Ready
    needs: [PyPI-Publish]
    uses: ./.github/workflows/ready.yml
    with:
      message: "Package has been published."
