name: Python package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEFAULT_PYTHON_VERSION: "3.10"
  PROJECT_NAME: sagemaker_rightline

jobs:
  pre_commit_check:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Pre-Commit
        id: pre_commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --show-diff-on-failure --all-files --color=always

  check_test_build:
    needs: [pre_commit_check]
    name: Build-Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update Pip
      run: pip install -U pip
    - name: Build with Dependencies
      run: pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest -vs ./tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
    - name: Build Package
      run: python3 -m build

  generate_docs:
    needs: [pre_commit_check]
    if: ${{ github.ref != 'refs/heads/main' }}
    name: Generate-Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stiebels/plantuml-e2e-action@bugfix-doc-version
        name: Generate Class Diagram
        with:
          puml_version: "1.2023.7"
          pip_install_deps_cmd: "pip install -e .[docs]"
          path: ${{ env.PROJECT_NAME }}
          module: ${{ env.PROJECT_NAME }}
          output_dir: "docs"
      - name: Commit changed files
        run: |
          git config user.email gh-actions
          git config user.name gh-actions
          git add .
          git commit -m "Committed updated class diagram"
          git config pull.rebase false
          git pull origin ${{ github.event.pull_request.head.ref }}
          git push origin HEAD:${{ github.event.pull_request.head.ref }}

  Ready:
    name: Ready
    needs: [check_test_build, generate_docs]
    uses: ./.github/workflows/ready.yml
    with:
      message: "Pre-Commit, test and build have been successful."
